// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rsshub/app/model/internal"
)

// RssFeedTag is the golang structure for table rss_feed_tag.
type RssFeedTag internal.RssFeedTag

// Fill with you ideas below.
