// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"rsshub/app/model/internal"
)

// RssFeedItem is the golang structure for table rss_feed_item.
type RssFeedItem internal.RssFeedItem

// Fill with you ideas below.
