// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// RssFeedChannel is the golang structure for table rss_feed_channel.
type RssFeedChannel struct {
	Id          string `orm:"id,primary"   json:"id"`          //
	Title       string `orm:"title"        json:"title"`       //
	ChannelDesc string `orm:"channel_desc" json:"channelDesc"` //
	ImageUrl    string `orm:"image_url"    json:"imageUrl"`    //
	Link        string `orm:"link"         json:"link"`        //
}
