// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// RssFeedTag is the golang structure for table rss_feed_tag.
type RssFeedTag struct {
	Name      string      `orm:"name"       json:"name"`      //
	ChannelId string      `orm:"channel_id" json:"channelId"` //
	Title     string      `orm:"title"      json:"title"`     //
	Date      *gtime.Time `orm:"date"       json:"date"`      //
}
