// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rsshub/app/dao/internal"
)

// rssFeedItemDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rssFeedItemDao struct {
	internal.RssFeedItemDao
}

var (
	// RssFeedItem is globally public accessible object for table rss_feed_item operations.
	RssFeedItem = rssFeedItemDao{
		internal.RssFeedItem,
	}
)

// Fill with you ideas below.
