// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rsshub/app/dao/internal"
)

// rssFeedTagDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rssFeedTagDao struct {
	internal.RssFeedTagDao
}

var (
	// RssFeedTag is globally public accessible object for table rss_feed_tag operations.
	RssFeedTag = rssFeedTagDao{
		internal.RssFeedTag,
	}
)

// Fill with you ideas below.
