// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"rsshub/app/dao/internal"
)

// rssFeedChannelDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rssFeedChannelDao struct {
	internal.RssFeedChannelDao
}

var (
	// RssFeedChannel is globally public accessible object for table rss_feed_channel operations.
	RssFeedChannel = rssFeedChannelDao{
		internal.RssFeedChannel,
	}
)

// Fill with you ideas below.
